### ISSUE TITLE
0.7 -> 0.9 upgrade caused reduced svg fidelity

### ISSUE THREAD

**Issue by liaden** [jonhoo/inferno#153]
I noticed this on rbspy specifically: https://github.com/rbspy/rbspy/issues/239

**Comment by jonhoo** [comment]
Hmm, interesting. I suspect this is due to https://github.com/jonhoo/inferno/pull/136. @jasonrhansen could you take a look? @liaden could you try generating the flamegraph with `min_width` set to a smaller value than the default and see if that fixes the issue?

**Comment by liaden** [comment]
Just removing https://github.com/rbspy/rbspy/blob/master/src/ui/flamegraph.rs#L35 to take the default value, it works as expected.

**Comment by jonhoo** [comment]
Ah, interesting! Yes, the _meaning_ of `min_with` changed in the move from 0.7 to 0.9 (I should probably have documented that in a changelog somewhere). It is not (from memory) a percentage of the image width rather than a pixel value. Should be a straightforward enough change to `rbspy` I think?

**Comment by liaden** [comment]
Yeah, it definitely seems more appropriate to change on rbspy side. 

> It is not (from memory) a percentage of the image width rather than a pixel value.
Did you mean _now_?

**Comment by jonhoo** [comment]
Ah, yes, sorry, now :sweat_smile:

**Comment by jonhoo** [comment]
I'll close this then since it is not an issue on the inferno side of things. Thanks for the report though!
