### ISSUE TITLE
Templated C++ functions cut off after opening parenthesis in template arguments.

### ISSUE THREAD

**Issue by SoftwareApe** [jonhoo/inferno#173]
Same issue as https://github.com/brendangregg/FlameGraph/pull/215 on the original tool.

**Comment by jonhoo** [comment]
Ah, yes, good catch! The Rust version of that code lives here:
https://github.com/jonhoo/inferno/blob/23df1d4aa6ef0d9533d782353d2cf51d834d8423/src/collapse/perf.rs#L604

It doesn't use regular expressions, but instead just walks the string in an equivalent way. Want to try putting up a PR that makes a similar change to the one you linked?

**Comment by SoftwareApe** [comment]
Thank you for the pointer. I can take a look. I was actually grepping for regex, since I assumed it was regex, but couldn't find it 😅 .

**Comment by SoftwareApe** [comment]
So it's kind of obvious what's happening. In the C++ stacks you have std::function<bool (...

Then it finds this parenthesis, and because the preceding char isn't "." it assumes this isn't Go (so far so good), but then it truncates the string after the parenthesis.

Ergo, we'd have to detect C++ stacks. However the preceding char (in this case, maybe compiler dependent? Is a space.

I think the easiest would be, we count the template/angle brackets ("<" and ">") to see if we're inside a template parameter (either they're balanced or unbalanced).

Do you think this is feasible?

**Comment by jonhoo** [comment]
Hmm, yeah, it's a tricky situation, and it's unfortunate we don't have more context. I _think_ my inclination here is to only strip "arguments" (in parentheses) when they appear at the tail end of an expression. So I think your plan to not strip if we're inside `<>` will work well!

**Comment by SoftwareApe** [comment]
I suggested a fix now. I added some tests for C++ stack collapse with std::function templates.

**Comment by SoftwareApe** [comment]
I'm not sure what's up with the tests, but 4 of them were failing before I changed anything.
