### ISSUE TITLE
In icicle mode, the bar at bottom should really be at the top

### ISSUE THREAD

**Issue by itamarst** [jonhoo/inferno#176]
When you mouseover a frame there's a little bar at the bottom of the diagram that shows info like "33% of samples" or "20% of RAM" or whatever.

In icicle mode most of the interesting info is at the top, and so you never actually get to see this bar if you have a long callstack. This is pretty much always the case for my use case—see e.g. https://pythonspeed.com/products/filmemoryprofiler/memory-graph.svg, where the really tall callstack on the left means you never get to see the bottom bar.

It seems that for icicle mode this bar should always be at the top.

I will attempt to write a PR for this.

**Comment by jonhoo** [comment]
Oh, yes, good catch! I wonder if this is the case for the official flamegraph too then — we re-use basically the same code as them. May be worth checking if anything has changed in their code, or if there are outstanding PRs there on this issue. Would very much like a PR here though regardless!

**Comment by itamarst** [comment]
Their code looks the same, and not seeing any PRs/issues.

**Comment by itamarst** [comment]
https://pythonspeed.com/products/filmemoryprofiler/ is how I'm using Inferno, BTW.

**Comment by jonhoo** [comment]
Thanks for checking! And that's neat — thanks for linking it :D
