### ISSUE TITLE
Consistent coloring, without input files?

### ISSUE THREAD

**Issue by saethlin** [jonhoo/inferno#189]
It seems like the only way to get consistently-colored flamegraphs is for every user to maintain a little database file of functions and their colors. This is inconvenient and makes coordinating work tricky; these mappings become another resource that needs to be version-controlled which is rather at odd with how explorative profiling tends to be.

Why isn't the coloring of a flamegraph deterministic by default? I have changes in my fork ready to go if anyone is interested.

**Comment by jonhoo** [comment]
Inferno uses the same default as the [original Perl implementation](https://github.com/brendangregg/FlameGraph/) uses. Whether that's a _good_ default I'm not sure, but I think it's valuable to stick decently closely to the original. You can opt into deterministic coloring by using the `hash` argument — does that work for you?

**Comment by saethlin** [comment]
Unfortunately not at all. For the codebases I care about, `--hash` picks almost exactly the same color for the whole flamegraph, because nearly all the functions are from the same crate.

I'm tempted to advocate for a new flag to produce the behavior that I want, but I really don't know what to call it because `--hash` exists.

**Comment by jonhoo** [comment]
You could use `consistent` or `deterministic`?

**Comment by saethlin** [comment]
Implementation: https://github.com/jonhoo/inferno/pull/190

**Comment by saethlin** [comment]
Closed by https://github.com/jonhoo/inferno/pull/190
