### ISSUE TITLE
Initial release of Firestorm

### ISSUE THREAD

**Issue by That3Percent** [jonhoo/inferno#208]
Firestorm uses `inferno` to display flames, so I thought you might like to know your hard work is appreciated.

[Firestorm README](https://github.com/That3Percent/firestorm/blob/master/README.md)

Scroll down to see screenshots of `inferno`. Then feel free to close this issue once acknowledged.

**Comment by jonhoo** [comment]
That's awesome, thank you for sharing! :heart: 
Also cc @jasonrhansen, @bcmyers, @itamarst, @Licenser, and @AnderEnder, who have been great contributors!
