### ISSUE TITLE
Icicle graphs

### ISSUE THREAD

**Issue by jonhoo** [jonhoo/inferno#22]
The [`--inverted` flag](https://github.com/brendangregg/FlameGraph/blob/f857ebc94bfe2a9bfdc4f1536ebacfb7466f69ba/flamegraph.pl#L149), apart from [changing the title of the plot](https://github.com/brendangregg/FlameGraph/blob/f857ebc94bfe2a9bfdc4f1536ebacfb7466f69ba/flamegraph.pl#L205), changes the flame graph such that the entire plot is [up-side-down](https://github.com/brendangregg/FlameGraph/blob/f857ebc94bfe2a9bfdc4f1536ebacfb7466f69ba/flamegraph.pl#L1067L1068) (note that this also affects [the JavaScript](https://github.com/brendangregg/FlameGraph/blob/f857ebc94bfe2a9bfdc4f1536ebacfb7466f69ba/flamegraph.pl#L864)). We should probably support that flag too.

**Comment by busarovalex** [comment]
May I take this issue?

**Comment by jonhoo** [comment]
Absolutely!
