### ISSUE TITLE
Flame chart mode

### ISSUE THREAD

**Issue by jonhoo** [jonhoo/inferno#23]
In `flamegraph.pl`, you can pass the [`--flamechart` flag](https://github.com/brendangregg/FlameGraph/blob/f857ebc94bfe2a9bfdc4f1536ebacfb7466f69ba/flamegraph.pl#L150) to produce a "flame chart" in which stacks frames are _not_ merged. To [quote Brendan](http://www.brendangregg.com/flamegraphs.html):

> Flame charts were first added by Google Chrome's WebKit Web Inspector ([bug](https://bugs.webkit.org/show_bug.cgi?id=111162)). While inspired by flame graphs, flame charts put the passage of time on the x-axis instead of the alphabet. This means that time-based patterns can studied. Flame graphs reorder the x-axis samples alphabetically, which maximizes frame merging, and better shows the big picture of the profile. Multi-threaded applications can't be shown sensibly by a single flame chart, whereas they can with a flame graphs (a problem flame charts didn't need to deal with, since it was initially used for single-threaded JavaScript analysis). Both visualizations are useful, and tools should make both available if possible (eg, TraceCompass does). Some analysis tools have implemented flame charts and mistakingly called them flame graphs.

I'm not _entirely_ sure how time factors into this, since the collapsed stacks don't have any timing information from the original execution in them, but people seem to find them useful, so let's implement them! Also, if you _do_ find them useful, please include docs and examples! If you just want to do the implementation work, that's fine too, just include the quoted explanation above somewhere in the docs.

In terms of code, `--flamechart` mainly [avoids sorting](https://github.com/brendangregg/FlameGraph/blob/f857ebc94bfe2a9bfdc4f1536ebacfb7466f69ba/flamegraph.pl#L605) the incoming stacks, and [changes the plot title](https://github.com/brendangregg/FlameGraph/blob/f857ebc94bfe2a9bfdc4f1536ebacfb7466f69ba/flamegraph.pl#L198).

**Comment by masklinn** [comment]
> I'm not _entirely_ sure how time factors into this, since the collapsed stacks don't have any timing information from the original execution in them

There's no specific time axis, but assuming a regular sample rate and the sampling source simply writes sample as they go (which seems like the intent given the format) each sample represents a time interval of sort, and so the entire sequence (and flamechart) is a timeline even if not specifically labelled thus.

**Comment by jonhoo** [comment]
@masklinn I guess what makes me feel weird about this is the fact that `stackcollapse` still happens first, and it also sorts the stacks, so what kind of timing information is still left at that point for `flamegraph` to draw from?

**Comment by jonhoo** [comment]
Ah, interesting, so the expectation is that in chart mode you _don't_ collapse the stacks? They still need to be in the right format though, no? Sorting is also _necessary_ in non-chart mode, otherwise the algorithm wouldn't correctly identify shared parents.

**Comment by masklinn** [comment]
> Ah, interesting, so the expectation is that in chart mode you don't collapse the stacks?

That's what I'd guess / assume. If I remember correctly flamegraph.pl does its own sorting and grouping. Unless I'm mistaken what the stackcollapse scripts do is mostly reformat stacks to the input format of flamegraph (usually from some multiline stack dump to the single-line stacks of flamegraph.pl).

> They still need to be in the right format though, no?

Sure but the input format of flamegraph.pl isn't exactly complex, IIRC brendan gregg had an example where he dumped one out of a dtrace script.

> Sorting is also necessary in non-chart mode, otherwise the algorithm wouldn't correctly identify shared parents.

Indeed, but as you link to in the issue description flamegraph.pl does that internally, it does not *need* a sorted and merged input.

**Comment by jonhoo** [comment]
Ah, I see what you mean. I think what this suggests is that we really want our collapsers to be split into two "halves". One that turns a particular input format into the "standard" collapsed format, and one that actually collapses stacks expressed in that format. For flame charts, you'd only use the first part, and not sort the flamegraph input. For regular flame graphs, you would use both parts, and also sort the flamegraph input. Does that seem right?

/cc @jasonrhansen

**Comment by masklinn** [comment]
possibly? I’m not too sure what you mean collapsing stacks. As far as I can tell all that was changed in pl is not sorting stacks before merging, such that it’s only merging stacks (frames?) which are adjacent in the input rather than across the entire file.
