### ISSUE TITLE
Semver break in 0.10.13

### ISSUE THREAD

**Issue by c-nixon** [jonhoo/inferno#233]
We happen to have cargo-flamegraph building in a part of our CI and have just started receiving the following error

```
    --> /opt/rust/cargo/registry/src/github.com-1ecc6299db9ec823/flamegraph-0.5.1/src/lib.rs:299:43
     |
 299 |             collapse_options.skip_after = Some(skip_after.into())
     |             ---------------------------   ^^^^^^^^^^^^^^^^^^^^^^^ expected struct `Vec`, found enum `Option`
     |             |
     |             expected due to the type of this binding
     |
     = note: expected struct `Vec<String>`
                  found enum `Option<_>`
```

It looks like it has ["0.10.8"](https://github.com/flamegraph-rs/flamegraph/blob/a9837efd8744dac853acbe3d476924083f26743d/Cargo.toml#L25) as the version in it's Cargo.toml

**Comment by jonhoo** [comment]
Ah yes, you're totally right! #231 is backwards incompatible for the library. I keep forgetting about that! I've yanked 0.10.13 and released as 0.11.0.
