### ISSUE TITLE
Not possible to set font in flamegraphs to default fonts

### ISSUE THREAD

**Issue by itamarst** [jonhoo/inferno#244]
In CSS I can do:

```
body {
     font-family: monospace;
}
```

but I can't do that with flamegraph, because it turns it into:

```
body {
     font-family: "monospace";
}
```

which means "the font called `monospace`" rather than "default monospace font".

**Comment by jonhoo** [comment]
Ah, yes, that happens here:
https://github.com/jonhoo/inferno/blob/b8b2f0d9dfab6f85acc42f65a8504b6baab69848/src/flamegraph/svg.rs#L125

I think we just need to teach that code path about the "special" font names so that it doesn't escape those! I'd be happy to take a look at a PR :+1:
