### ISSUE TITLE
itoa with separators that avoids allocation

### ISSUE THREAD

**Issue by bcmyers** [jonhoo/inferno#29]
Hey Jon. Just watched your most recent stream. I wrote a crate recently that does itoa with thousands separators without allocation. It's not up on crates.io yet, but will be shortly. [num-format](https://github.com/bcmyers/num-format).

**Comment by bcmyers** [comment]
Just got the first version of num-format up on crates.io; so hopefully I'll find some time in the coming weeks to help out here with a pull request. Would love to help out!

**Comment by jonhoo** [comment]
@bcmyers see also the more general case in https://github.com/jonhoo/inferno/issues/33

**Comment by jonhoo** [comment]
Now that the fix to #33 has landed (#37), I wonder whether this is still relevant? Maybe..
