### ISSUE TITLE
`Input data ends in the middle of a stack.` when using on result of attaching

### ISSUE THREAD

**Issue by HKalbasi** [jonhoo/inferno#292]
When I use `perf script | inferno-collapse-dtrace > stacks.folded` on a file generated by `perf record --call-graph dwarf -p <pid>  -g` which is used to generate perf data for an already open process, I get this error:
```
Error: Custom { kind: InvalidData, error: "Input data ends in the middle of a stack." }
```
Which is probably telling truth, but is it possible to recover from this state instead of bailing out?

**Comment by jonhoo** [comment]
Ah, this is because you're trying to use `perf script` with the `dtrace` collapser. You'll want to use the `perf` collapser instead:
```console
$ perf script | inferno-collapse-perf > stacks.folded
```
