### ISSUE TITLE
graph diffs from perl flamegraph

### ISSUE THREAD

**Issue by Orca-bit** [jonhoo/inferno#318]
I use the same `perf.data`

1. when using perl flamegraph, the total `samples` shows `295730188910`
2. when using rs flamegraph, the total `samples` shows `36277`
3. when using perf report, it shows `Samples: 36K of event cycles, Event count: 295730188910`

that makes graphes look diff
results with perl flamegraph is more closely match the percentages shown in perf report

flamegraph-rs/flamegraph#328

**Comment by Orca-bit** [comment]
brendangregg/FlameGraph#165

**Comment by jonhoo** [comment]
Fix in https://github.com/jonhoo/inferno/pull/319 (thanks!)

**Comment by jonhoo** [comment]
Released in 0.11.20 (#324) :tada:
