### ISSUE TITLE
Provide magic collapse-dispatcher

### ISSUE THREAD

**Issue by jonhoo** [jonhoo/inferno#81]
Once #78 lands, we'll have two different `Collapse` implementations. It'd be cool to have a `inferno-collapse-guess`, which attempts to use whichever `Collapse` implementation is appropriate for a given input! This may end up being a little tricky, but here's a sketch of how it might work:

 - Add a method `is_applicable(&str) -> Option<bool>` to `Collapse`. `None` means "not sure -- need more input", `Some(true)` means "yes, this implementation should work with that string, and `Some(false)` means "no, this implementation definitely won't work.
 - Add a new collapse implementation, "guess", which internally buffers the string it reads from the underlying streams, and knows about all the other `Collapse` impls (maybe using something like [`inventory`](https://crates.io/crates/inventory)?). For each line it reads, it calls `is_applicable` on all impls that haven't returned `Some(false)` thus far with the input it has collected. If any of them return `Some(true)`, it decides to use that impl, and then:
 - Implements `BufRead` for a struct that wraps a `String` plus a `BufRead`. The `String` is the string the guesser has read so far, and that's what it'll read from first. Once all of that string has been read, it proceeds to read from the `BufRead`.

**Comment by jasonrhansen** [comment]
Won't we need to use `Collapse` as a trait object to implement this? The current definition of `Collapse` isn't object safe since both `collapse` and `collapse_file` have generic type parameters.

**Comment by jonhoo** [comment]
Yeah, it'll be a little annoying, but may be doable by not having a list of things to iterate over, but instead doing some kind of macro stuff + a list of variables instead. It ain't pretty, but it'll be better (I think) than trying to make `Collapse` object safe. The alternative would be to make `Collapse` object safe by taking `dyn` arguments instead of making them generic.

**Comment by jasonrhansen** [comment]
I'd rather keep the generic type parameters. I'm going to give it a try and see what I come up with.
