### ISSUE TITLE
Add iterator interface to that returns structs for each event.

### ISSUE THREAD

**Issue by Licenser** [jonhoo/inferno#95]
It might be nice to a struct for stacks, an then split it into reader, collapse, 'renderer' 

That would allow not having to convert a stack to a string and then back from a string to data to render flame graphs and also generalize the rendering logic.

**Comment by jonhoo** [comment]
Are you thinking of something like https://github.com/jonhoo/inferno/issues/30 ?

**Comment by Licenser** [comment]
Abselutely, sorry the topic didn't give it away :) I'll comment on that.
